version: "3"
services:
  db:
    image: postgres
    container_name: auth-db-dev
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  redis:
    image: redis
    container_name: auth-redis-dev
    ports:
      - 6379:6379
