version: '3.8'

x-env: &x-env
  env_file:
  - env

services:
  auth-db:
    container_name: auth-db
    image: postgres
    networks:
      - movies-network
    <<: *x-env

  auth-redis:
    container_name: auth-redis
    image: redis
    networks:
      - movies-network

  auth-api:
    container_name: auth-api
    build:
      context: auth/
    networks:
      - movies-network
    depends_on:
      - auth-db
      - auth-redis
    <<: *x-env

  ucg-api:
    container_name: ucg-api
    build:
      context: events_api/
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - movies-network
    depends_on:
      - auth-api
    <<: *x-env

networks:
  movies-network:
    name: movies-network
    driver: bridge