version: '3.8'

x-env: &x-env
  env_file:
  - env

services:
  uga-api:
    container_name: ugc-api
    build:
      context: uga_api/
    volumes:
      - ./uga_api/:/app/
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - movies-network
    <<: *x-env
  etl:
    build:
      context: etl/
    image: uga_etl
    container_name: ugc_etl
    restart: on-failure
    <<: *x-env
  nginx:
    container_name: ugc-nginx
    image: nginx:1.19.5
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - /tmp/logs/nginx/:/var/log/nginx/
    ports:
      - 5001:80
    depends_on:
      - uga-api
    networks:
      - movies-network
  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    environment:
      ES_HOST: "elasticsearch:9200"
    ports:
      - "5044:5044/udp"
    volumes:
      - ./logging/logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
    volumes:
      - /tmp/esdata:/tmp/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.3.2
    volumes:
      - /tmp/logs/nginx:/var/log/nginx:ro
      - ./logging/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - uga-api
      - nginx
      - logstash
      - elasticsearch
      - kibana
    links:
      - logstash

networks:
  movies-network:
    name: movies-api-network
    driver: bridge