version: "3"

x-env: &x-env
  env_file:
  - env


services:
  auth-db:
    image: postgres
    container_name: auth-db-dev
    ports:
      - 5432:5432
    networks:
      - movies-network
    <<: *x-env

  auth-redis:
    image: redis
    container_name: auth-redis-dev
    ports:
      - 6379:6379
    networks:
      - movies-network
  auth-api:
    container_name: auth-api
    build:
      context: auth/
    ports:
      - 5000:5000
    networks:
      - movies-network
    depends_on:
      - auth-db
      - auth-redis
    <<: *x-env

networks:
  movies-network:
    name: movies-network
    driver: bridge