version: '3.8'

x-env: &x-env
  env_file:
  - env

services:
  ucg-api:
    container_name: ucg-api
    build:
      context: ug—Å_api/
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - movies-network
    depends_on:
      - auth-api
    <<: *x-env
  etl:
    build:
      context: etl/
    image: ugc_etl
    container_name: ugc_etl
    restart: on-failure
    <<: *x-env

networks:
  movies-network:
    name: movies-network
    driver: bridge