@startuml
<style>
    package {
        RoundCorner 10
    }
    component {
        RoundCorner 10
    }
    arrow {
      LineThickness 1.5
    }
</style>
actor Клиент as Client

package FilmService as FS {
    component Nginx

    database PostgreSQL
    database ElasticSearch
    database Redis
    database MongoDB

    package "Admin Panel" as AP {
        component Django
        component moviesETL
    }
    package "AuthAPI" as Auth {
        component AuthFastAPI
    }
    package "AsyncAPI" as Async {
        component AsyncFastAPI
    }
    package "UGA" as UGA {
        component Kafka
        component ugaAPI
        component ugaETL
        component ClickHouse
    }
    package "UGC" as UGC {
        component ugcAPI
    }
}

left to right direction
Client --> Nginx

Nginx --> Django: Панель администратора
moviesETL <--> PostgreSQL: Обновление данных
moviesETL <--> ElasticSearch: Обновление данных
Django --> PostgreSQL

Nginx --> AuthFastAPI: Авторизация
AuthFastAPI <--> PostgreSQL
AuthFastAPI <--> Redis: Данные о токенах

Nginx --> AsyncFastAPI: Поиск
AsyncFastAPI --> AuthFastAPI: проверка авторизации
AsyncFastAPI --> ElasticSearch: Запрос на поиск
AsyncFastAPI --> Redis: Кэширование запросов

Nginx --> ugaAPI: Пользовательская активность
ugaAPI --> Kafka: Данные о просмотрах фильмов
Kafka <--> ugaETL: Обновление данных
ugaETL <-> ClickHouse

Nginx --> ugcAPI: Пользовательский контент
ugcAPI --> AuthFastAPI: Проверка авторизации
ugcAPI --> MongoDB: Данные о закладках, оценках и отзывах
@enduml
