version: "3.8"

services:
  vertica:
    image: jbfavre/vertica
    hostname: vertica
    volumes:
      - ugc_bench_vertica_data:/home/dbadmin/docker
    ports:
      - 5433:5433

volumes:
  ugc_bench_vertica_data: