name: Python application

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - uses: wemake-services/wemake-python-styleguide@master
      with:
        reporter: 'github-pr-review'
      env:
        GITHUB_TOKEN: ${{ secrets.wemake_token }}
