name: Python application

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide@0.15.3
      with:
          reporter: 'github-pr-review'
      env:
        GITHUB_TOKEN: ${{ secrets.wemake_token }}
